name: ingestion_executor
source:
  type: kafka
  config:
    connection:
      bootstrap: ${KAFKA_BOOTSTRAP_SERVER:-localhost:9092}
      schema_registry_url: ${SCHEMA_REGISTRY_URL:-http://localhost:8081}
    topic_routes:
      mcl: ${METADATA_CHANGE_LOG_VERSIONED_TOPIC_NAME:-MetadataChangeLog_Versioned_v1}
      pe: ${PLATFORM_EVENT_TOPIC_NAME:-PlatformEvent_v1}
filter:
  event_type: MetadataChangeLogEvent_v1
  event:
    entityType: dataHubExecutionRequest
    changeType: UPSERT
    aspectName:
      - dataHubExecutionRequestInput
      - dataHubExecutionRequestSignal
    aspect:
      value:
        executorId: ${EXECUTOR_ID:-default}
action:
  type: executor
  config:
    executor_id: default
    task_configs:
      - name: RUN_INGEST
        type: datahub_kubernetes.executor.execution.kubernetes_pod_ingestion_task.KubernetesPodIngestionTask
        configs:
          image_template: hub.teko.vn/dataops/datahub/ingestion:0.10.3
          k8s_config:
            in_cluster: ${KUBERNETES_IN_CLUSTER:-false}
            config_file: ${KUBERNETES_CONFIG_FILE:-null}
            namespace: ${KUBERNETES_NAMESPACE:-default}
datahub:
  server: "${DATAHUB_GMS_PROTOCOL:-http}://${DATAHUB_GMS_HOST:-localhost}:${DATAHUB_GMS_PORT:-8080}"
  extra_headers:
    Authorization: "Basic ${DATAHUB_SYSTEM_CLIENT_ID:-__datahub_system}:${DATAHUB_SYSTEM_CLIENT_SECRET:-JohnSnowKnowsNothing}"
